# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/r-ver:4.1.0
ARG BUILD_DATE=2021-08-18
WORKDIR /home/rstudio
RUN MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN apt-get update && apt-get install libcurl4-openssl-dev
RUN install2.r --error --skipinstalled \ 
  curl \ 
  dplyr \ 
  fs \ 
  here \ 
  jsonlite \ 
  lubridate \ 
  magrittr \ 
  purrr \ 
  readr \ 
  stringr
